# Major Map: An AI-Powered Academic Planner and Predictor for SJSU Students

## 1. Data Loading

In [1]:
!rm -rf major_map
!git clone https://github.com/7HE-LUCKY-FISH/major_map.git

Cloning into 'major_map'...
remote: Enumerating objects: 1119, done.
remote: Counting objects: 100% (209/209), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 1119 (delta 115), reused 89 (delta 68), pack-reused 910 (from 2)
Receiving objects: 100% (1119/1119), 2.64 MiB | 3.97 MiB/s, done.
Resolving deltas: 100% (464/464), done.

In [2]:
!ls /content/

major_map  sample_data

In [3]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from pathlib import Path

In [4]:
# Path to repo in Colab
data_dir = Path("major_map/data/csv_data")

# Get all csv files
csv_files = sorted(data_dir.glob("*.csv"))

print("Found CSV files:")
for f in csv_files:
    print(" -", f.name)

# Combine all the csv files into one
# Check method number 4: https://medium.com/@stella96joshua/how-to-combine-multiple-csv-files-using-python-for-your-analysis-a88017c6ff9e
df_original = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)

Found CSV files:
 - Fall-2022.csv
 - Fall-2023.csv
 - Fall-2024.csv
 - Spring-2022.csv
 - Spring-2023.csv
 - Spring-2024.csv
 - Spring-2025.csv

## 2. Data Understanding

### 2a. Basic Inspection

In [5]:
df_original.head()

,Section,Number,Mode,Title,Satisfies,Unit,Type,Days,Times,Instructor,Location,Dates,Seats,Year,Semester
0,BIOL 10 (Section 01),40529,In Person,The Living World,GE: B2,3,LEC,TR,09:00AM-10:15AM,Allison Harness,SCI164,08/19/22-12/06/22,59,2022,Fall
1,BIOL 10 (Section 03),40060,In Person,The Living World,GE: B2,3,LEC,MW,10:30AM-11:45AM,Phillip Hawkins,SCI164,08/19/22-12/06/22,42,2022,Fall
2,BIOL 10 (Section 04),47603,Fully Online,The Living World,GE: B2,3,LEC,TBA,TBA,Phillip Hawkins,ONLINE,08/19/22-12/06/22,6,2022,Fall
3,BIOL 10 (Section 99),41828,Fully Online,The Living World,GE: B2,3,LEC,TBA,TBA,Mary Poffenroth,ONLINE,08/19/22-12/06/22,1,2022,Fall
4,CHEM 1A (Section 01),40081,In Person,General Chemistry,GE: B1+B3,5,LEC,MWF,09:30AM-10:20AM,Resa Kelly,SCI142,08/19/22-12/06/22,0,2022,Fall

In [6]:
df_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4007 entries, 0 to 4006
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Section     4007 non-null   object
 1   Number      4007 non-null   int64
 2   Mode        4007 non-null   object
 3   Title       4007 non-null   object
 4   Satisfies   1615 non-null   object
 5   Unit        4007 non-null   int64
 6   Type        4007 non-null   object
 7   Days        4007 non-null   object
 8   Times       4007 non-null   object
 9   Instructor  4007 non-null   object
 10  Location    3945 non-null   object
 11  Dates       4007 non-null   object
 12  Seats       4007 non-null   int64
 13  Year        4007 non-null   int64
 14  Semester    4007 non-null   object
dtypes: int64(4), object(11)
memory usage: 469.7+ KB

In [7]:
df_original['Year'].value_counts()

Year
2024    1191
2022    1127
2023    1115
2025     574
Name: count, dtype: int64

In [8]:
df_original['Semester'].value_counts()

Semester
Spring    2160
Fall      1847
Name: count, dtype: int64

In [9]:
df_original['Instructor'].nunique()

646

In [10]:
df_original['Section'].nunique()

980

### 2b. Check Missing / Special Values

In [11]:
df_original['Times'].value_counts().head(10)

Times
10:30AM-11:45AM    371
12:00PM-01:15PM    366
09:00AM-10:15AM    316
01:30PM-02:45PM    300
03:00PM-04:15PM    263
04:30PM-05:45PM    185
06:00PM-08:45PM    138
TBA                102
09:00AM-11:45AM    102
03:00PM-05:45PM     97
Name: count, dtype: int64

In [12]:
df_original['Days'].value_counts().head(10)

Days
MW      1120
TR       989
F        400
T        343
W        310
R        289
M        229
MTWR     113
TBA      102
MWF       86
Name: count, dtype: int64

In [13]:
print(df_original['Instructor'].value_counts())
print('\n-----------------------------\n')
print(df_original['Section'].value_counts())
print('\n-----------------------------\n')
print(df_original['Semester'].value_counts())

Instructor
Richard Low                                 53
Padmavati Tanniru                           52
Alla Petrosyan                              51
Olga Kovaleva                               48
Medha Bodas                                 47
                                            ..
Neomi Millan                                 1
Peter Beyersdorf / Kenneth Wharton           1
Ehsan Khatami                                1
Nargis Adham / Azadeh Shahid Faylienejad     1
Resa Kelly                                   1
Name: count, Length: 646, dtype: int64

-----------------------------

Section
ENGR 100W (Section 16)    14
ENGR 100W (Section 14)    14
ENGR 100W (Section 06)    14
ENGR 100W (Section 18)    11
ENGR 100W (Section 12)    10
                          ..
CMPE 165 (Section 80)      1
CS 100W (Section 84)       1
CS 146 (Section 81)        1
CS 146 (Section 82)        1
CS 147 (Section 81)        1
Name: count, Length: 980, dtype: int64

-----------------------------

Semester
Spring    2160
Fall      1847
Name: count, dtype: int64

## 3. Data Preprocessing

In this section we will go through each features and analyze what is the best way to preprocess the data so they can be useful to use for the machine leanring model.

In [14]:
df_preprocess = df_original.copy()
df_preprocess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4007 entries, 0 to 4006
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Section     4007 non-null   object
 1   Number      4007 non-null   int64
 2   Mode        4007 non-null   object
 3   Title       4007 non-null   object
 4   Satisfies   1615 non-null   object
 5   Unit        4007 non-null   int64
 6   Type        4007 non-null   object
 7   Days        4007 non-null   object
 8   Times       4007 non-null   object
 9   Instructor  4007 non-null   object
 10  Location    3945 non-null   object
 11  Dates       4007 non-null   object
 12  Seats       4007 non-null   int64
 13  Year        4007 non-null   int64
 14  Semester    4007 non-null   object
dtypes: int64(4), object(11)
memory usage: 469.7+ KB

### 3a. "Section" Feature

Ex: BIOL 10 (Section 01)
* Just in case, convert every value in "Section" to a string type. If something was not a string (like a number or a missing value NaN), it becomes a string (NaN --> "nan").

* Removes any leading and trailing whitespaces from each string. This is so we can split "Section" into "Dept" and "CourseNumber", or just "Course".

In [15]:
df_preprocess['Section'] = df_preprocess['Section'].astype(str).str.strip()
print("Missing Section:", df_preprocess['Section'].isna().sum())
print(df_preprocess['Section'].head())

Missing Section: 0
0    BIOL 10 (Section 01)
1    BIOL 10 (Section 03)
2    BIOL 10 (Section 04)
3    BIOL 10 (Section 99)
4    CHEM 1A (Section 01)
Name: Section, dtype: object

### 3g. "Type" Feature

* The types are LEC, SEM and LAB. Will do one hot encoding later.

In [16]:
print("Unique Type values:", df_preprocess['Type'].unique())

Unique Type values: ['LEC' 'SEM' 'LAB']

### 3h. "Days" Feature

* Give us the day patterns. TBA is a special flag. TBA is usually online and asyn classes.

In [17]:
print("Missing Days:", df_preprocess['Days'].isna().sum())
print("Unique Days values:", df_preprocess['Days'].unique())
print(df_preprocess['Days'].value_counts().sort_index())

Missing Days: 0
Unique Days values: ['TR' 'MW' 'TBA' 'MWF' 'F' 'T' 'W' 'R' 'M' 'S' 'MTWR']
Days
F        400
M        229
MTWR     113
MW      1120
MWF       86
R        289
S         26
T        343
TBA      102
TR       989
W        310
Name: count, dtype: int64

### 3i. "Times" Feature

* Give the time range (start time and end time) of a section

In [18]:
print("Missing Times:", df_preprocess['Times'].isna().sum())
print(df_preprocess['Times'].value_counts())

Missing Times: 0
Times
10:30AM-11:45AM    371
12:00PM-01:15PM    366
09:00AM-10:15AM    316
01:30PM-02:45PM    300
03:00PM-04:15PM    263
                  ...
01:30PM-02:24PM      1
03:00PM-03:45PM      1
12:00AM-01:15AM      1
06:00PM-08:20PM      1
08:00AM-09:15AM      1
Name: count, Length: 114, dtype: int64

### 3j. "Instructor" Feature

* Give us the professor name

In [19]:
print("Missing Instructor:", df_preprocess['Instructor'].isna().sum())
print("Number of unique instructors:", df_preprocess['Instructor'].nunique())
print(df_preprocess['Instructor'].unique)

Missing Instructor: 0
Number of unique instructors: 646
<bound method Series.unique of 0                 Allison Harness
1                 Phillip Hawkins
2                 Phillip Hawkins
3                 Mary Poffenroth
4                      Resa Kelly
                  ...
4002    Azadeh Shahid Faylienejad
4003      Vakini Santhanakrishnan
4004               Ramen Bahuguna
4005                 Nargis Adham
4006               Ramen Bahuguna
Name: Instructor, Length: 4007, dtype: object>

### 3n. "Year" Feature

* Calendar Year: should be only 2022, 2023, 2024 and 2025

In [20]:
print("Missing Year:", df_preprocess['Year'].isna().sum())
print("Years:", df_preprocess['Year'].unique())

Missing Year: 0
Years: [2022 2023 2024 2025]

### 3o. "Semester" Feature

* Term name: We only focus on Fall and Spring (no Winter or Summer)

In [21]:
print("Missing Semester:", df_preprocess['Semester'].isna().sum())
print("Semesters:", df_preprocess['Semester'].unique())

Missing Semester: 0
Semesters: ['Fall' 'Spring']

In [22]:
df_preprocess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4007 entries, 0 to 4006
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Section     4007 non-null   object
 1   Number      4007 non-null   int64
 2   Mode        4007 non-null   object
 3   Title       4007 non-null   object
 4   Satisfies   1615 non-null   object
 5   Unit        4007 non-null   int64
 6   Type        4007 non-null   object
 7   Days        4007 non-null   object
 8   Times       4007 non-null   object
 9   Instructor  4007 non-null   object
 10  Location    3945 non-null   object
 11  Dates       4007 non-null   object
 12  Seats       4007 non-null   int64
 13  Year        4007 non-null   int64
 14  Semester    4007 non-null   object
dtypes: int64(4), object(11)
memory usage: 469.7+ KB

## 4. Data Engineering

In [23]:
# Make a copy for data engineering
df_engineer = df_preprocess.copy()

Originally, we have a total of 15 features:
1. Section          (original)
2. Number           (original, not used as feature)
3. Mode             (original, categorical feature)
4. Title            (original, usually not used as feature in v1)
5. satisfies         (original, optional categorical feature)
6. Unit             (original, numeric feature)
7. Type             (original, categorical feature)
8. Days             (original, used to build slot, not as input feature)
9. Times            (original, used to build StartMinutes/slot)
10. Instructor      (original, used to create instructor_id target)
11. Location        (original)
12. Dates           (original, not used as feature)
13. Seats           (original)
14. Year            (original, numeric feature)
15. Semester        (original, categorical feature)

New Features we will get from data engineering:
1. Dept            (engineered from Section)
2. CourseNumber    (engineered from Section)
3. CourseCode     (engineered from Dept + CourseNumber, optional)
4. HasGE           (engineered from satisfies, 0/1 flag, optional)
5. StartMinutes    (engineered from Times)
6. EndMinutes      (engineered from Times)
7. DurationMinutes (engineered from End-Start)
7. Slot            (engineered from Days + StartMinutes, e.g. "MWF_540")
8. instructor_id   (engineered target from Instructor)
9. slot_id         (engineered target from slot)
10. Building        (engineered from Location, e.g. "SCI", "MD", "ONLINE")
12. Term            (engineered from Year + Semester, e.g. "2022_Fall")
13. SemesterIndex   (engineered from term, 0,1,2,... in time order)

---

### 4a. Section → Dept, CourseNumber, and CourseCode

In [24]:
section = df_engineer['Section'].str.extract(r'^(\w+)\s+([^\s]+)')

df_engineer['Dept'] = section[0]
df_engineer['CourseNumber'] = section[1]
df_engineer['CourseCode'] = df_engineer['Dept'].astype(str) + ' ' + df_engineer['CourseNumber'].astype(str)
df_engineer[['Section', 'Dept', 'CourseNumber', 'CourseCode']].head()

                Section  Dept CourseNumber CourseCode
0  BIOL 10 (Section 01)  BIOL           10    BIOL 10
1  BIOL 10 (Section 03)  BIOL           10    BIOL 10
2  BIOL 10 (Section 04)  BIOL           10    BIOL 10
3  BIOL 10 (Section 99)  BIOL           10    BIOL 10
4  CHEM 1A (Section 01)  CHEM           1A    CHEM 1A

### 4b. Times → StartMinutes and EndMinutes

* Minutes after midnight (00:00 am)

In [25]:
def parse_time_range(s):
  if s == "TBA" or "-" not in s:
    return -1, -1, -1

  # s looks like "09:00AM-10:15AM"
  # split the start and end with '-'
  start_str, end_str = s.split('-')

  # parse each part as time
  # format='%I:%M%p'
  # %I = hour in 12-hour clock (01-12)
  # %M = minutes (00-59)
  # %p = AM/PM
  start_dt = pd.to_datetime(start_str, format='%I:%M%p')
  end_dt   = pd.to_datetime(end_str,   format='%I:%M%p')

  # convert to "minutes since midnight"
  start_min = start_dt.hour * 60 + start_dt.minute
  end_min = end_dt.hour * 60 + end_dt.minute

  # section duration
  duration_min = end_min - start_min

  return start_min, end_min, duration_min

# Apply to df_model['Times'] and create three new columns
df_engineer[['StartMinutes', 'EndMinutes', 'DurationMinutes']] = df_engineer['Times'].apply(
    lambda s: pd.Series(parse_time_range(s))
)

df_engineer[['Times', 'StartMinutes', 'EndMinutes', 'DurationMinutes']].head()

             Times  StartMinutes  EndMinutes  DurationMinutes
0  09:00AM-10:15AM           540         615               75
1  10:30AM-11:45AM           630         705               75
2              TBA            -1          -1               -1
3              TBA            -1          -1               -1
4  09:30AM-10:20AM           570         620               50

### 4c. Days + StartMinutes + EndMinutes → Slot

* This show use the day and start minute. This feature is important for schedule planning later.

* We will later turn them into Slot_ID

In [26]:
def make_slot(row):
    days = str(row['Days']).strip()
    start = int(row['StartMinutes'])
    end   = int(row['EndMinutes'])

    # If this was a TBA row that you encoded as -1
    if start == -1 or end == -1:
        return days + '_TBA'

    return f"{days}_{start}_{end}"

df_engineer['Slot'] = df_engineer.apply(make_slot, axis=1)
df_engineer[['Days', 'Times', 'StartMinutes', 'Slot']].head()

  Days            Times  StartMinutes         Slot
0   TR  09:00AM-10:15AM           540   TR_540_615
1   MW  10:30AM-11:45AM           630   MW_630_705
2  TBA              TBA            -1      TBA_TBA
3  TBA              TBA            -1      TBA_TBA
4  MWF  09:30AM-10:20AM           570  MWF_570_620

### 4f. Semester → SemesterIndex

* Sort the unique terms and assing 0, 1, 2,... in time order

In [27]:
sem_order = {'Spring': 0, 'Fall': 1}

# Unique (Year, Semester) combos
term_df = (
    df_engineer[['Year', 'Semester']]
    .drop_duplicates()
    .copy()
)


# Sort by Year, then Spring/Fall
term_df['sem_order'] = term_df['Semester'].map(sem_order)
term_df = term_df.sort_values(['Year', 'sem_order']).reset_index(drop=True)

# Assign 0,1,2,... as SemesterIndex
term_df['SemesterIndex'] = term_df.index

print(term_df)

# Merge into df_engineer
df_engineer = df_engineer.merge(
    term_df[['Year', 'Semester', 'SemesterIndex']],
    on=['Year', 'Semester'],
    how='left'
)

print(
    df_engineer[['Year', 'Semester', 'SemesterIndex']]
    .drop_duplicates()
    .sort_values('SemesterIndex')
)

   Year Semester  sem_order  SemesterIndex
0  2022   Spring          0              0
1  2022     Fall          1              1
2  2023   Spring          0              2
3  2023     Fall          1              3
4  2024   Spring          0              4
5  2024     Fall          1              5
6  2025   Spring          0              6
      Year Semester  SemesterIndex
1847  2022   Spring              0
0     2022     Fall              1
2384  2023   Spring              2
590   2023     Fall              3
2873  2024   Spring              4
1216  2024     Fall              5
3433  2025   Spring              6

In [28]:
print(df_engineer.info())
print("-------------------------------------------")
df_engineer.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4007 entries, 0 to 4006
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Section          4007 non-null   object
 1   Number           4007 non-null   int64
 2   Mode             4007 non-null   object
 3   Title            4007 non-null   object
 4   Satisfies        1615 non-null   object
 5   Unit             4007 non-null   int64
 6   Type             4007 non-null   object
 7   Days             4007 non-null   object
 8   Times            4007 non-null   object
 9   Instructor       4007 non-null   object
 10  Location         3945 non-null   object
 11  Dates            4007 non-null   object
 12  Seats            4007 non-null   int64
 13  Year             4007 non-null   int64
 14  Semester         4007 non-null   object
 15  Dept             4007 non-null   object
 16  CourseNumber     4007 non-null   object
 17  CourseCode       4007 non-null   object
 18  StartMinutes     4007 non-null   int64
 19  EndMinutes       4007 non-null   int64
 20  DurationMinutes  4007 non-null   int64
 21  Slot             4007 non-null   object
 22  SemesterIndex    4007 non-null   int64
dtypes: int64(8), object(15)
memory usage: 720.1+ KB
None
-------------------------------------------

,Section,Number,Mode,Title,Satisfies,Unit,Type,Days,Times,Instructor,...,Year,Semester,Dept,CourseNumber,CourseCode,StartMinutes,EndMinutes,DurationMinutes,Slot,SemesterIndex
0,BIOL 10 (Section 01),40529,In Person,The Living World,GE: B2,3,LEC,TR,09:00AM-10:15AM,Allison Harness,...,2022,Fall,BIOL,10,BIOL 10,540,615,75,TR_540_615,1
1,BIOL 10 (Section 03),40060,In Person,The Living World,GE: B2,3,LEC,MW,10:30AM-11:45AM,Phillip Hawkins,...,2022,Fall,BIOL,10,BIOL 10,630,705,75,MW_630_705,1
2,BIOL 10 (Section 04),47603,Fully Online,The Living World,GE: B2,3,LEC,TBA,TBA,Phillip Hawkins,...,2022,Fall,BIOL,10,BIOL 10,-1,-1,-1,TBA_TBA,1
3,BIOL 10 (Section 99),41828,Fully Online,The Living World,GE: B2,3,LEC,TBA,TBA,Mary Poffenroth,...,2022,Fall,BIOL,10,BIOL 10,-1,-1,-1,TBA_TBA,1
4,CHEM 1A (Section 01),40081,In Person,General Chemistry,GE: B1+B3,5,LEC,MWF,09:30AM-10:20AM,Resa Kelly,...,2022,Fall,CHEM,1A,CHEM 1A,570,620,50,MWF_570_620,1

**Recency-Weighted Combined Schedule Prediction Model**

## Overview

* Train the model to predict if a course will be scheduled or not
    *
    * Course: CourseCode, Instructor, Slot, and Type

* When The user picks desired course/type/time preferences, we will:
    * build a feature row for each requested course
    * run the model

## Code Implementation

In [29]:
df_combined = df_engineer.copy()
print(df_combined.head())

                Section  Number          Mode              Title  Satisfies  \
0  BIOL 10 (Section 01)   40529     In Person   The Living World     GE: B2
1  BIOL 10 (Section 03)   40060     In Person   The Living World     GE: B2
2  BIOL 10 (Section 04)   47603  Fully Online   The Living World     GE: B2
3  BIOL 10 (Section 99)   41828  Fully Online   The Living World     GE: B2
4  CHEM 1A (Section 01)   40081     In Person  General Chemistry  GE: B1+B3

   Unit Type Days            Times       Instructor  ...  Year Semester  Dept  \
0     3  LEC   TR  09:00AM-10:15AM  Allison Harness  ...  2022     Fall  BIOL
1     3  LEC   MW  10:30AM-11:45AM  Phillip Hawkins  ...  2022     Fall  BIOL
2     3  LEC  TBA              TBA  Phillip Hawkins  ...  2022     Fall  BIOL
3     3  LEC  TBA              TBA  Mary Poffenroth  ...  2022     Fall  BIOL
4     5  LEC  MWF  09:30AM-10:20AM       Resa Kelly  ...  2022     Fall  CHEM

   CourseNumber CourseCode StartMinutes EndMinutes DurationMinutes  \
0            10    BIOL 10          540        615              75
1            10    BIOL 10          630        705              75
2            10    BIOL 10           -1         -1              -1
3            10    BIOL 10           -1         -1              -1
4            1A    CHEM 1A          570        620              50

          Slot  SemesterIndex
0   TR_540_615              1
1   MW_630_705              1
2      TBA_TBA              1
3      TBA_TBA              1
4  MWF_570_620              1

[5 rows x 23 columns]

In [30]:
display(df_combined.columns)

Index(['Section', 'Number', 'Mode', 'Title', 'Satisfies', 'Unit', 'Type',
       'Days', 'Times', 'Instructor', 'Location', 'Dates', 'Seats', 'Year',
       'Semester', 'Dept', 'CourseNumber', 'CourseCode', 'StartMinutes',
       'EndMinutes', 'DurationMinutes', 'Slot', 'SemesterIndex'],
      dtype='object')

### 1. Combined Model Setup

In [31]:
df_combined['Scheduled'] = 1

# TERM AGNOSTIC MODEL
Only run if testing term agnostic model

In [32]:
# Columns that define a "complete course"
key_cols = ['CourseCode', 'Instructor', 'Slot', 'Type']

# We'll use Dept only for negative generation constraints (not required as a model input)
helper_cols = ['Dept']

pos_raw = df_combined.copy()

# Keep only needed cols; drop missing; dedupe across ALL terms (term-agnostic)
pos = (
    pos_raw[key_cols + helper_cols]
    .dropna(subset=key_cols)
    .drop_duplicates()
    .reset_index(drop=True)
)

pos['ScheduledEver'] = 1

# Fast lookup set of "ever scheduled" combos
pos_keys = set(map(tuple, pos[key_cols].values))
print("Unique positive combos:", len(pos))

Unique positive combos: 2678

Get pools of instructors for each department
and slots for each course

In [33]:
# Instructors historically associated with each Dept
instr_pool = (
    pos[['Dept', 'Instructor']]
    .drop_duplicates()
    .groupby('Dept')['Instructor']
    .apply(list)
)

# Slots historically used for each (CourseCode, Type)
slot_pool = (
    pos[['CourseCode', 'Type', 'Slot']]
    .drop_duplicates()
    .groupby(['CourseCode', 'Type'])['Slot']
    .apply(list)
)

In [34]:
rng = np.random.default_rng(42)
K = 3  # negatives per positive combo
MAX_TRIES_PER_POS = 25 * K

neg_rows = []

# For each positive course we are generating 3 negatives
for _, row in pos.iterrows():
    dept = row['Dept']
    course = row['CourseCode']
    typ = row['Type']
    instr = row['Instructor']
    slot = row['Slot']

    i_pool = instr_pool.get(dept, [])
    s_pool = slot_pool.get((course, typ), [])

    # Need at least one alternative instructor OR one alternative slot to generate negatives
    if len(i_pool) < 2 and len(s_pool) < 2:
        continue

    generated = 0
    tries = 0

    # Keep going until we have K # of negatives or we exceed tries
    while generated < K and tries < MAX_TRIES_PER_POS:
        tries += 1
        new = row.copy()

        r = rng.random()

        if r < 0.50 and len(i_pool) >= 2:
            # swap instructor within dept
            choices = [i for i in i_pool if i != instr]
            if not choices:
                continue
            new['Instructor'] = rng.choice(choices)

        elif r < 0.90 and len(s_pool) >= 2:
            # swap slot within course+type feasible slots
            choices = [s for s in s_pool if s != slot]
            if not choices:
                continue
            new['Slot'] = rng.choice(choices)

        else:
            # swap both (if possible)
            if len(i_pool) >= 2:
                choices_i = [i for i in i_pool if i != instr]
                if not choices_i:
                    continue
                new['Instructor'] = rng.choice(choices_i)
            if len(s_pool) >= 2:
                choices_s = [s for s in s_pool if s != slot]
                if not choices_s:
                    continue
                new['Slot'] = rng.choice(choices_s)

        key = (new['CourseCode'], new['Instructor'], new['Slot'], new['Type'])

        # If it's a known historical combo, skip (it's actually positive)
        if key in pos_keys:
            continue

        new['ScheduledEver'] = 0
        neg_rows.append(new[key_cols + ['ScheduledEver']])
        generated += 1

neg = pd.DataFrame(neg_rows).drop_duplicates(subset=key_cols).reset_index(drop=True)

# Only taking the key cols and not helper
df_term_agnostic = pd.concat(
    [
        pos[key_cols + ['ScheduledEver']],
        neg[key_cols + ['ScheduledEver']]
    ],
    ignore_index=True
).drop_duplicates(subset=key_cols + ['ScheduledEver'])

print(df_term_agnostic['ScheduledEver'].value_counts())
print("Total labeled combos:", len(df_term_agnostic))

ScheduledEver
0    7007
1    2678
Name: count, dtype: int64
Total labeled combos: 9685

### ML Model for term agnostic dataset

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

df_model = df_term_agnostic.copy()

# Add interaction columns (still derived only from the 4 inputs)
df_model['Course_Instructor'] = df_model['CourseCode'].astype(str) + "||" + df_model['Instructor'].astype(str)
df_model['Course_Slot']       = df_model['CourseCode'].astype(str) + "||" + df_model['Slot'].astype(str)
df_model['Instructor_Slot']   = df_model['Instructor'].astype(str) + "||" + df_model['Slot'].astype(str)
df_model['Course_Type']       = df_model['CourseCode'].astype(str) + "||" + df_model['Type'].astype(str)

cat_cols = ['CourseCode', 'Instructor', 'Slot', 'Type',
            'Course_Instructor', 'Course_Slot', 'Instructor_Slot', 'Course_Type']
# cat_cols = ['CourseCode', 'Instructor', 'Slot', 'Type',]

X = df_model[cat_cols]
y = df_model['ScheduledEver'].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

preprocess = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
    ],
    remainder='drop'
)

clf = LogisticRegression(
    max_iter=2000,
    solver='saga',
    class_weight='balanced'
)

model = Pipeline(steps=[
    ('prep', preprocess),
    ('clf', clf)
])

model.fit(X_train, y_train)

proba = model.predict_proba(X_test)[:, 1]
pred = (proba >= 0.5).astype(int)

print("ROC AUC:", roc_auc_score(y_test, proba))
print("PR AUC :", average_precision_score(y_test, proba))
print(classification_report(y_test, pred, digits=3))

ROC AUC: 0.6175759319036509
PR AUC : 0.38024427543557304
              precision    recall  f1-score   support

           0      0.780     0.732     0.755      1401
           1      0.396     0.459     0.425       536

    accuracy                          0.657      1937
   macro avg      0.588     0.596     0.590      1937
weighted avg      0.674     0.657     0.664      1937

**Note: We can adjust the prediction cut-off ratio to see how that affects results**

# Set Method (NO ML)

In [36]:
pos_key_set = set(map(tuple, pos[key_cols].values))

def scheduled_ever_lookup(course, instructor, slot, typ):
    return int((course, instructor, slot, typ) in pos_key_set)

# TERM INCLUDED MODEL
History features added that are built from prior term information

In [37]:
def make_prior_count_table(df_pos, group_cols, term_col, out_col):
    """
    For each (group, term), count how many positives occur in that term,
    then compute cumulative positives strictly BEFORE that term.
    """
    tmp = (
        df_pos.groupby(group_cols + [term_col])
              .size()
              .reset_index(name='n_in_term')
              .sort_values(term_col)
    )
    # cumulative up through current term, then subtract current term => strictly prior
    tmp[out_col] = tmp.groupby(group_cols)['n_in_term'].cumsum() - tmp['n_in_term']
    return tmp[group_cols + [term_col, out_col]]

def make_last_seen_term_table(df_pos, group_cols, term_col, out_col):
    """
    For each (group, term) where group appears, compute the previous term
    where it appeared (strictly before).
    """
    tmp = (
        df_pos[group_cols + [term_col]]
        .drop_duplicates()
        .sort_values(group_cols + [term_col])
    )
    tmp[out_col] = tmp.groupby(group_cols)[term_col].shift(1)
    return tmp[group_cols + [term_col, out_col]]

In [38]:
def add_history_features(df_labeled, term_col='SemesterIndex'):
    df = df_labeled.copy()
    df[term_col] = df[term_col].astype(int)

    # Only positives define "what happened historically"
    df_pos = df[df['Scheduled'] == 1].copy()

    # ---- PRIOR COUNT FEATURES ----
    feature_defs = [
        (['Instructor'],                   'instr_prior_count'),
        (['CourseCode'],                   'course_prior_count'),
        (['Slot'],                         'slot_prior_count'),
        (['CourseCode','Type'],            'course_type_prior_count'),
        (['Instructor','Dept'],            'instr_dept_prior_count'),
        (['Instructor','CourseCode'],      'instr_course_prior_count'),
        (['CourseCode','Slot'],            'course_slot_prior_count'),
        (['CourseCode','Type','Slot'],     'course_type_slot_prior_count'),
        (['CourseCode','Instructor','Slot','Type'], 'combo_prior_count'),
    ]

    for group_cols, out_col in feature_defs:
        tbl = make_prior_count_table(df_pos, group_cols, term_col, out_col)
        df = df.merge(tbl, on=group_cols + [term_col], how='left')
        df[out_col] = df[out_col].fillna(0).astype(int)

    # ---- LAST SEEN / RECENCY FEATURES (OPTIONAL BUT VERY STRONG) ----
    recency_defs = [
        (['Instructor'], 'instr_last_term'),
        (['CourseCode'], 'course_last_term'),
        (['Instructor','CourseCode'], 'instr_course_last_term'),
        (['CourseCode','Instructor','Slot','Type'], 'combo_last_term'),
    ]

    max_term = df[term_col].max()

    for group_cols, out_col in recency_defs:
        tbl = make_last_seen_term_table(df_pos, group_cols, term_col, out_col)
        df = df.merge(tbl, on=group_cols + [term_col], how='left')
        # if never seen before, set last_term to -1
        df[out_col] = df[out_col].fillna(-1).astype(int)

        # add another column that shows how long it has been since that term was seen
        gap_col = out_col.replace('last_term', 'terms_since')
        # changes the terms_since column to df[term_col] - df[out_col]
        # unless df[out_col] == -1, then it changes to (max_term + 1) instead
        df[gap_col] = np.where(df[out_col] == -1, (max_term + 1), (df[term_col] - df[out_col]))
        df[gap_col] = df[gap_col].astype(int)

    # ---- LOG TRANSFORMS (often helps linear models since the counts are very skewed like 0,0,0,1,0,20,200…) ----
    count_cols = [c for c in df.columns if c.endswith('_prior_count')]
    for c in count_cols:
        df[c + '_log1p'] = np.log1p(df[c].astype(float))

    return df

In [39]:
def add_history_features_no_leak(df_labeled, df_pos_hist, term_col='SemesterIndex'):
    """
    df_labeled: rows to featurize (train+test, includes negatives)
    df_pos_hist: ONLY positives from TRAIN TERMS (history allowed)
    """
    df = df_labeled.copy()
    df[term_col] = df[term_col].astype(int)

    hist = df_pos_hist.copy()
    hist[term_col] = hist[term_col].astype(int)

    # keep original order so merges can sort then restore
    df["_row_id"] = np.arange(len(df))

    # ---- PRIOR COUNT FEATURES ----
    feature_defs = [
        (['Instructor'],                   'instr_prior_count'),
        (['CourseCode'],                   'course_prior_count'),
        (['Slot'],                         'slot_prior_count'),
        (['CourseCode','Type'],            'course_type_prior_count'),
        (['Instructor','Dept'],            'instr_dept_prior_count'),
        (['Instructor','CourseCode'],      'instr_course_prior_count'),
        (['CourseCode','Slot'],            'course_slot_prior_count'),
        (['CourseCode','Type','Slot'],     'course_type_slot_prior_count'),
        (['CourseCode','Instructor','Slot','Type'], 'combo_prior_count'),
    ]

    for group_cols, out_col in feature_defs:
        tmp = (
            hist.groupby(group_cols + [term_col])
                .size()
                .reset_index(name='n_in_term')
                .sort_values(term_col, kind="mergesort")
        )
        tmp['cum_inclusive'] = tmp.groupby(group_cols)['n_in_term'].cumsum()

        lookup = tmp[group_cols + [term_col, 'cum_inclusive']].rename(
            columns={'cum_inclusive': out_col}
        )

        left  = df.sort_values(term_col, kind="mergesort").reset_index(drop=True)
        right = lookup.sort_values(term_col, kind="mergesort").reset_index(drop=True)

        left = pd.merge_asof(
            left, right,
            on=term_col,
            by=group_cols,
            direction='backward',
            allow_exact_matches=False
        )

        left[out_col] = left[out_col].fillna(0).astype(int)
        df = left.sort_values("_row_id", kind="mergesort").reset_index(drop=True)

    # ---- LAST SEEN / RECENCY FEATURES ----
    recency_defs = [
        (['Instructor'], 'instr_last_term'),
        (['CourseCode'], 'course_last_term'),
        (['Instructor','CourseCode'], 'instr_course_last_term'),
        (['CourseCode','Instructor','Slot','Type'], 'combo_last_term'),
    ]

    for group_cols, out_col in recency_defs:
        seen = (
            hist[group_cols + [term_col]]
            .drop_duplicates()
            .sort_values(term_col, kind="mergesort")
            .reset_index(drop=True)
        )
        # keep the seen term as a payload column (merge_asof only keeps one copy of 'on')
        seen[out_col] = seen[term_col]
        seen = seen[group_cols + [term_col, out_col]]

        left  = df.sort_values(term_col, kind="mergesort").reset_index(drop=True)
        right = seen.sort_values(term_col, kind="mergesort").reset_index(drop=True)

        left = pd.merge_asof(
            left, right,
            on=term_col,
            by=group_cols,
            direction='backward',
            allow_exact_matches=False
        )

        left[out_col] = left[out_col].fillna(-1).astype(int)

        gap_col = out_col.replace('last_term', 'terms_since')
        left[gap_col] = np.where(
            left[out_col] == -1,
            left[term_col] + 1,          # never seen before
            left[term_col] - left[out_col]
        ).astype(int)

        df = left.sort_values("_row_id", kind="mergesort").reset_index(drop=True)

    # ---- LOG TRANSFORMS ----
    count_cols = [c for c in df.columns if c.endswith('_prior_count')]
    for c in count_cols:
        df[c + '_log1p'] = np.log1p(df[c].astype(float))

    df.drop(columns=["_row_id"], inplace=True)
    return df

**Code starts here**

1) First thing is get the active instructors for each dept+term and time slots used for each coursecode and type

In [40]:
pos = df_combined.copy()
pos['Scheduled'] = 1

# A term+dept -> list of active instructors
instr_pool = (
    pos[['SemesterIndex', 'Dept', 'Instructor']]
    .drop_duplicates()
    .groupby(['SemesterIndex', 'Dept'])['Instructor']
    .apply(list)
)

# A (course, type) -> list of historically used slots
# You can tighten this to (course, type, semester) if you want.
slot_pool = (
    pos[['CourseCode', 'Type', 'Slot']]
    .drop_duplicates()
    .groupby(['CourseCode', 'Type'])['Slot']
    .apply(list)
)

# Build a fast lookup set of positives (term-aware!)
pos_keys = set(
    zip(pos['SemesterIndex'], pos['CourseCode'], pos['Instructor'], pos['Slot'], pos['Type'])
)

2) Generate the negatives

In [41]:
rng = np.random.default_rng(42)
K = 3  # negatives per positive row

neg_rows = []

for _, row in pos.iterrows():
    term = row['SemesterIndex']
    dept = row['Dept']
    course = row['CourseCode']
    typ = row['Type']
    instr = row['Instructor']
    slot = row['Slot']

    #we swap from the pools to create negatives
    i_pool = instr_pool.get((term, dept), [])
    s_pool = slot_pool.get((course, typ), [])

    if len(i_pool) < 2 or len(s_pool) < 1:
        continue

    for _ in range(K):
        new = row.copy()

        # choose what to corrupt
        r = rng.random()
        if r < 0.5:
            # swap instructor within same term+dept
            choices = [i for i in i_pool if i != instr]
            if not choices:
                continue
            new_instr = rng.choice(choices)
            new['Instructor'] = new_instr

        elif r < 0.9:
            # swap slot within feasible slots for (course,type)
            if len(s_pool) > 1:
                choices = [s for s in s_pool if s != slot]
                new_slot = rng.choice(choices)
            else:
                continue
            new['Slot'] = new_slot

        else:
            # swap both
            choices_i = [i for i in i_pool if i != instr]
            if not choices_i:
                continue
            new['Instructor'] = rng.choice(choices_i)
            new['Slot'] = rng.choice(s_pool)

        key = (new['SemesterIndex'], new['CourseCode'], new['Instructor'], new['Slot'], new['Type'])
        if key in pos_keys:
            continue  # accidentally created a real positive

        new['Scheduled'] = 0
        neg_rows.append(new)

neg = pd.DataFrame(neg_rows).drop_duplicates(
    subset=['SemesterIndex', 'CourseCode', 'Instructor', 'Slot', 'Type']
)

df_labeled = pd.concat([pos, neg], ignore_index=True)
print(df_labeled['Scheduled'].value_counts())

Scheduled
0    10328
1     4007
Name: count, dtype: int64

3) Add the history features

In [42]:
# df_feat = add_history_features(df_labeled, term_col='SemesterIndex')

In [43]:
# 1) define your feature columns
cat_cols = ['CourseCode', 'Instructor', 'Slot', 'Type']
# include selected history features (you can add/remove)
num_cols = [
    'instr_prior_count_log1p',
    'course_prior_count_log1p',
    'slot_prior_count_log1p',
    'course_type_prior_count_log1p',
    'instr_dept_prior_count_log1p',
    'instr_course_prior_count_log1p',
    'course_slot_prior_count_log1p',
    'course_type_slot_prior_count_log1p',
    'combo_prior_count_log1p',

    #recency features (how long since the last occurrence)
    'instr_terms_since',
    'course_terms_since',
    'instr_course_terms_since',
    'combo_terms_since',
]

# --- time split first ---
all_terms = sorted(df_labeled['SemesterIndex'].unique())
test_terms = all_terms[-2:]

train_mask = ~df_labeled['SemesterIndex'].isin(test_terms)
test_mask  =  df_labeled['SemesterIndex'].isin(test_terms)

# IMPORTANT: history is built ONLY from TRAIN positives
train_pos_hist = df_labeled.loc[train_mask & (df_labeled['Scheduled'] == 1)].copy()

# compute features for ALL rows, using TRAIN history only
df_feat = add_history_features_no_leak(df_labeled, train_pos_hist, term_col='SemesterIndex')

# now build X/y from df_feat (same as before)
X = df_feat[cat_cols + num_cols].copy()
y = df_feat['Scheduled'].astype(int)

X_train, X_test = X.loc[train_mask], X.loc[test_mask]
y_train, y_test = y.loc[train_mask], y.loc[test_mask]

4) Split the data and train the model

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score, confusion_matrix

# # 1) define your feature columns
# cat_cols = ['CourseCode', 'Instructor', 'Slot', 'Type']
# # include selected history features (you can add/remove)
# num_cols = [
#     'instr_prior_count_log1p',
#     'course_prior_count_log1p',
#     'course_type_prior_count_log1p',
#     'instr_course_prior_count_log1p',
#     'course_type_slot_prior_count_log1p',
#     'combo_prior_count_log1p',
#     'instr_terms_since',
#     'course_terms_since',
#     'instr_course_terms_since',
#     'combo_terms_since',
# ]

# X = df_feat[cat_cols + num_cols].copy()
# y = df_feat['Scheduled'].astype(int)

# # 2) time-based split (same idea you had)
# all_terms = sorted(df_feat['SemesterIndex'].unique())
# test_terms = all_terms[-2:]

# train_mask = ~df_feat['SemesterIndex'].isin(test_terms)
# test_mask  =  df_feat['SemesterIndex'].isin(test_terms)

# X_train, X_test = X.loc[train_mask], X.loc[test_mask]
# y_train, y_test = y.loc[train_mask], y.loc[test_mask]

# 2.5) Add compute history

# 3) preprocessing + model
preprocess = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
        ('num', StandardScaler(), num_cols),
    ],
    remainder='drop'
)

clf = LogisticRegression(
    max_iter=2000,
    solver='saga',           # good for sparse one-hot
    class_weight='balanced'  # helps if negatives >> positives
)

model = Pipeline(steps=[
    ('prep', preprocess),
    ('clf', clf)
])

# 4) train + evaluate
model.fit(X_train, y_train)

proba = model.predict_proba(X_test)[:, 1]
pred  = (proba >= 0.5).astype(int)

print("Confusion matrix:\n", confusion_matrix(y_test, pred))
print("\nClassification report:\n", classification_report(y_test, pred, digits=3))
print("\nROC AUC:", roc_auc_score(y_test, proba))
print("PR AUC :", average_precision_score(y_test, proba))

Confusion matrix:
 [[2381  690]
 [ 480  725]]

Classification report:
               precision    recall  f1-score   support

           0      0.832     0.775     0.803      3071
           1      0.512     0.602     0.553      1205

    accuracy                          0.726      4276
   macro avg      0.672     0.688     0.678      4276
weighted avg      0.742     0.726     0.733      4276


ROC AUC: 0.7662473601932682
PR AUC : 0.5913624386286019

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, average_precision_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import ComplementNB
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

# --- preprocess variants ---
# For linear models: scaling helps; keep sparse-friendly scaling (with_mean=False)
preprocess_linear = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
        ('num', StandardScaler(with_mean=False), num_cols),
    ],
    remainder='drop'
)

# For Naive Bayes: DON'T standardize (it creates negatives and breaks the NB assumptions).
# Your numeric features are already nonnegative (log1p counts, terms_since), so passthrough is fine.
preprocess_nb = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
        ('num', 'passthrough', num_cols),
    ],
    remainder='drop'
)

def eval_model(name, preprocess, clf, X_train, y_train, X_test, y_test):
    pipe = Pipeline([('prep', preprocess), ('clf', clf)])
    pipe.fit(X_train, y_train)

    # score for AUC/PR-AUC
    if hasattr(pipe, "predict_proba"):
        scores = pipe.predict_proba(X_test)[:, 1]
        preds = (scores >= 0.5).astype(int)
    else:
        # e.g. LinearSVC without calibration
        scores = pipe.decision_function(X_test)
        preds = (scores >= 0).astype(int)

    print(f"\n=== {name} ===")
    print("ROC AUC:", roc_auc_score(y_test, scores))
    print("PR  AUC:", average_precision_score(y_test, scores))
    print(classification_report(y_test, preds, digits=3))
    return pipe

models = [
    ("LogReg (ElasticNet)",
     preprocess_linear,
     LogisticRegression(
         max_iter=4000,
         solver="saga",
         penalty="elasticnet",
         l1_ratio=0.2,           # try 0.1, 0.5 too
         C=1.0,
         class_weight="balanced"
     )),

    ("Linear SVM (Calibrated)",
     preprocess_linear,
     CalibratedClassifierCV(
         estimator=LinearSVC(class_weight="balanced"),
         method="sigmoid",
         cv=3
     )),

    ("ComplementNB",
     preprocess_nb,
     ComplementNB(alpha=0.5)),  # try 0.1, 1.0
]

fitted = {}
for name, prep, clf in models:
    fitted[name] = eval_model(name, prep, clf, X_train, y_train, X_test, y_test)

=== LogReg (ElasticNet) ===
ROC AUC: 0.7670094080482521
PR  AUC: 0.5926818578526293
              precision    recall  f1-score   support

           0      0.833     0.776     0.803      3071
           1      0.513     0.602     0.554      1205

    accuracy                          0.727      4276
   macro avg      0.673     0.689     0.679      4276
weighted avg      0.743     0.727     0.733      4276


=== Linear SVM (Calibrated) ===
ROC AUC: 0.7524661841264351
PR  AUC: 0.5782117806803332
              precision    recall  f1-score   support

           0      0.763     0.969     0.854      3071
           1      0.749     0.235     0.358      1205

    accuracy                          0.762      4276
   macro avg      0.756     0.602     0.606      4276
weighted avg      0.759     0.762     0.714      4276


=== ComplementNB ===
ROC AUC: 0.6959951953152973
PR  AUC: 0.5517626664211454
              precision    recall  f1-score   support

           0      0.816     0.724     0.767      3071
           1      0.453     0.584     0.511      1205

    accuracy                          0.684      4276
   macro avg      0.635     0.654     0.639      4276
weighted avg      0.714     0.684     0.695      4276

In [46]:
from xgboost import XGBClassifier

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
scale_pos_weight = neg / max(pos, 1)

xgb = XGBClassifier(
    n_estimators=600,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_lambda=1.0,
    min_child_weight=1.0,
    objective="binary:logistic",
    eval_metric="logloss",
    scale_pos_weight=scale_pos_weight,
    tree_method="hist"
)

xgb_model = eval_model("XGBoost", preprocess_nb, xgb, X_train, y_train, X_test, y_test)

=== XGBoost ===
ROC AUC: 0.7982260768992759
PR  AUC: 0.6451743446956492
              precision    recall  f1-score   support

           0      0.830     0.847     0.838      3071
           1      0.588     0.558     0.572      1205

    accuracy                          0.765      4276
   macro avg      0.709     0.702     0.705      4276
weighted avg      0.762     0.765     0.763      4276

## Neural Network Model

In [47]:
# Import TensorFlow/Keras for neural network
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Set random seeds for reproducibility
tf.random.set_seed(42)
np.random.seed(42)

In [48]:
def create_neural_network(input_dim, hidden_units=[256, 128, 64], dropout_rate=0.3):
    """
    Creates a feedforward neural network for binary classification.

    Architecture:
    - Input layer: Receives preprocessed features (one-hot + scaled numerical)
    - Hidden layers: Multiple dense layers with ReLU activation
    - Dropout: Regularization to prevent overfitting (randomly drops neurons during training)
    - Output layer: Single neuron with sigmoid activation for binary probability

    Parameters:
    - input_dim: Number of input features (determined after preprocessing)
    - hidden_units: List of neurons per hidden layer (e.g., [128, 64, 32])
    - dropout_rate: Fraction of neurons to randomly drop (0.3 = 30%)

    Returns:
    - Compiled Keras model ready for training
    """

    # Initialize sequential model (layers stacked one after another)
    model = keras.Sequential(name="CourseSchedulingNN")

    # Input layer - explicitly define input shape
    model.add(layers.Input(shape=(input_dim,), name="input"))

    # Build hidden layers
    for i, units in enumerate(hidden_units):
        # Dense (fully connected) layer with ReLU activation
        # ReLU(x) = max(0, x) - simple, effective non-linearity
        model.add(layers.Dense(
            units=units,                    # Number of neurons in this layer
            activation='relu',              # Activation function
            kernel_regularizer=keras.regularizers.l2(0.001),  # L2 penalty to prevent large weights
            name=f"hidden_{i+1}"
        ))

        # Batch Normalization: Normalizes activations to stabilize training
        # Helps network learn faster and be less sensitive to initialization
        model.add(layers.BatchNormalization(name=f"batchnorm_{i+1}"))

        # Dropout: Randomly sets dropout_rate fraction of inputs to 0 during training
        # Forces network to learn robust features, prevents overfitting
        model.add(layers.Dropout(dropout_rate, name=f"dropout_{i+1}"))

    # Output layer: Single neuron with sigmoid activation
    # Sigmoid(x) = 1 / (1 + e^(-x)) maps to [0, 1] range (probability)
    model.add(layers.Dense(1, activation='sigmoid', name="output"))

    # Compile model with optimizer, loss function, and metrics
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.001),  # Adam: Adaptive learning rate optimizer
        loss='binary_crossentropy',      # Standard loss for binary classification
        metrics=[
            'accuracy',                   # Track accuracy during training
            keras.metrics.Precision(name='precision'),      # TP / (TP + FP)
            keras.metrics.Recall(name='recall'),            # TP / (TP + FN)
            keras.metrics.AUC(name='auc')                   # Area under ROC curve
        ]
    )

    return model

# Display model architecture summary
# This will show layer types, output shapes, and parameter counts
sample_model = create_neural_network(input_dim=100)  # Dummy input_dim for visualization
sample_model.summary()

Model: "CourseSchedulingNN"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ hidden_1 (Dense)                │ (None, 256)            │        25,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batchnorm_1                     │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_2 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batchnorm_2                     │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_3 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batchnorm_3                     │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 68,865 (269.00 KB)

 Trainable params: 67,969 (265.50 KB)

 Non-trainable params: 896 (3.50 KB)

In [49]:
# Preprocess data for neural network
# Transform training and test sets using the same preprocessing as other models
X_train_nn = preprocess_nb.fit_transform(X_train)
X_test_nn = preprocess_nb.transform(X_test)

# Convert sparse matrix to dense array (Keras needs dense arrays)
if hasattr(X_train_nn, 'toarray'):
    X_train_nn = X_train_nn.toarray()
    X_test_nn = X_test_nn.toarray()

# Get number of features after preprocessing
input_dim = X_train_nn.shape[1]
print(f"Number of input features after preprocessing: {input_dim}")

# Calculate class weights for imbalanced data
# Same concept as scale_pos_weight in XGBoost
neg_count = (y_train == 0).sum()
pos_count = (y_train == 1).sum()
total = len(y_train)

class_weights = {
    0: total / (2 * neg_count),  # Weight for negative class
    1: total / (2 * pos_count)   # Weight for positive class (higher due to fewer samples)
}

print(f"\nClass distribution:")
print(f"  Negatives: {neg_count} (weight: {class_weights[0]:.3f})")
print(f"  Positives: {pos_count} (weight: {class_weights[1]:.3f})")
print(f"  Ratio: 1:{neg_count/pos_count:.1f}")

Number of input features after preprocessing: 900

Class distribution:
  Negatives: 7257 (weight: 0.693)
  Positives: 2802 (weight: 1.795)
  Ratio: 1:2.6

In [50]:
# Create and train the neural network model
print("Creating Neural Network model...")

# Build the model
nn_model = create_neural_network(
    input_dim=input_dim,
    hidden_units=[128, 64, 32],  # 3 hidden layers
    dropout_rate=0.3             # 30% dropout
)

# Define callbacks for training
callbacks = [
    # EarlyStopping: Stop training if validation loss doesn't improve
    # Prevents overfitting by stopping before model starts memorizing training data
    keras.callbacks.EarlyStopping(
        monitor='val_loss',           # Metric to watch
        patience=5,                   # Stop if no improvement for 5 epochs
        restore_best_weights=True,    # Restore weights from best epoch
        verbose=1
    ),
    # ReduceLROnPlateau: Reduce learning rate when learning plateaus
    # Helps fine-tune model by taking smaller steps when close to optimum
    keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,                   # Reduce learning rate by half
        patience=3,                   # Wait 3 epochs before reducing
        min_lr=1e-6,                  # Don't go below this learning rate
        verbose=1
    )
]

# Train the model
print("\nTraining Neural Network...")
print("This may take a few minutes...")

history = nn_model.fit(
    X_train_nn, y_train,
    epochs=50,                    # Maximum number of training iterations
    batch_size=256,               # Process 256 samples before updating weights
    validation_split=0.1,         # Use 10% of training data for validation
    class_weight=class_weights,   # Apply class weights to handle imbalance
    callbacks=callbacks,
    verbose=1                     # Show progress bar (set to 0 to hide)
)

print("\n✅ Training complete!")

# Evaluate on test set
print("\n=== Neural Network (3-layer) ===")

# Get predictions
y_pred_proba = nn_model.predict(X_test_nn).flatten()  # Probabilities
y_pred = (y_pred_proba >= 0.5).astype(int)            # Binary predictions

# Calculate metrics
roc_auc = roc_auc_score(y_test, y_pred_proba)
pr_auc = average_precision_score(y_test, y_pred_proba)

print("ROC AUC:", roc_auc)
print("PR  AUC:", pr_auc)
print(classification_report(y_test, y_pred, digits=3))

Creating Neural Network model...

Training Neural Network...
This may take a few minutes...
Epoch 1/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 12s 149ms/step - accuracy: 0.5542 - auc: 0.5794 - loss: 1.2013 - precision: 0.3590 - recall: 0.5607 - val_accuracy: 0.2356 - val_auc: 0.0000e+00 - val_loss: 1.0002 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 0.0010
Epoch 2/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5799 - auc: 0.6286 - loss: 1.0236 - precision: 0.3871 - recall: 0.6128 - val_accuracy: 0.8101 - val_auc: 0.0000e+00 - val_loss: 0.8780 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 0.0010
Epoch 3/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5877 - auc: 0.6460 - loss: 0.9631 - precision: 0.3936 - recall: 0.6142 - val_accuracy: 0.9145 - val_auc: 0.0000e+00 - val_loss: 0.7880 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 0.0010
Epoch 4/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6011 - auc: 0.6636 - loss: 0.9310 - precision: 0.4061 - recall: 0.6246 - val_accuracy: 0.9334 - val_auc: 0.0000e+00 - val_loss: 0.7321 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 0.0010
Epoch 5/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6036 - auc: 0.6700 - loss: 0.9033 - precision: 0.4084 - recall: 0.6263 - val_accuracy: 0.9225 - val_auc: 0.0000e+00 - val_loss: 0.7410 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 0.0010
Epoch 6/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6187 - auc: 0.6879 - loss: 0.8761 - precision: 0.4237 - recall: 0.6442 - val_accuracy: 0.9433 - val_auc: 0.0000e+00 - val_loss: 0.6705 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 0.0010
Epoch 7/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6255 - auc: 0.6983 - loss: 0.8531 - precision: 0.4299 - recall: 0.6431 - val_accuracy: 0.9215 - val_auc: 0.0000e+00 - val_loss: 0.6912 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 0.0010
Epoch 8/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6500 - auc: 0.7223 - loss: 0.8268 - precision: 0.4555 - recall: 0.6706 - val_accuracy: 0.9026 - val_auc: 0.0000e+00 - val_loss: 0.6760 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 0.0010
Epoch 9/50
19/36 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6534 - auc: 0.7260 - loss: 0.8164 - precision: 0.4713 - recall: 0.6655
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6492 - auc: 0.7258 - loss: 0.8126 - precision: 0.4546 - recall: 0.6685 - val_accuracy: 0.8410 - val_auc: 0.0000e+00 - val_loss: 0.7148 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 0.0010
Epoch 10/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6646 - auc: 0.7365 - loss: 0.7987 - precision: 0.4707 - recall: 0.6706 - val_accuracy: 0.7922 - val_auc: 0.0000e+00 - val_loss: 0.7240 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 5.0000e-04
Epoch 11/50
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6667 - auc: 0.7446 - loss: 0.7834 - precision: 0.4731 - recall: 0.6742 - val_accuracy: 0.8330 - val_auc: 0.0000e+00 - val_loss: 0.7087 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - learning_rate: 5.0000e-04
Epoch 11: early stopping
Restoring model weights from the end of the best epoch: 6.

✅ Training complete!

=== Neural Network (3-layer) ===
134/134 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
ROC AUC: 0.7444038799585468
PR  AUC: 0.5747167995073976
              precision    recall  f1-score   support

           0      0.789     0.920     0.850      3071
           1      0.647     0.373     0.473      1205

    accuracy                          0.766      4276
   macro avg      0.718     0.646     0.661      4276
weighted avg      0.749     0.766     0.743      4276

### Comparing All Models

Now let's compare all models side-by-side to see which performs best:

In [53]:
# Compare all models we've trained
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score

# Store results for each model
results = []

# Evaluate each model from the 'fitted' dictionary
for model_name, model in fitted.items():
    scores = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else model.decision_function(X_test)
    preds = (scores >= 0.5).astype(int) if hasattr(model, "predict_proba") else (scores >= 0).astype(int)

    results.append({
        'Model': model_name,
        'ROC AUC': roc_auc_score(y_test, scores),
        'PR AUC': average_precision_score(y_test, scores),
        'Precision': precision_score(y_test, preds),
        'Recall': recall_score(y_test, preds),
        'F1-Score': f1_score(y_test, preds)
    })

# Add XGBoost
xgb_scores = xgb_model.predict_proba(X_test)[:, 1]
xgb_preds = (xgb_scores >= 0.5).astype(int)
results.append({
    'Model': 'XGBoost',
    'ROC AUC': roc_auc_score(y_test, xgb_scores),
    'PR AUC': average_precision_score(y_test, xgb_scores),
    'Precision': precision_score(y_test, xgb_preds),
    'Recall': recall_score(y_test, xgb_preds),
    'F1-Score': f1_score(y_test, xgb_preds)
})

# Add Neural Network
nn_scores = y_pred_proba  # Already computed above
nn_preds = y_pred         # Already computed above
results.append({
    'Model': 'Neural Network',
    'ROC AUC': roc_auc_score(y_test, nn_scores),
    'PR AUC': average_precision_score(y_test, nn_scores),
    'Precision': precision_score(y_test, nn_preds),
    'Recall': recall_score(y_test, nn_preds),
    'F1-Score': f1_score(y_test, nn_preds)
})

# Create comparison DataFrame
comparison_df = pd.DataFrame(results)
comparison_df = comparison_df.sort_values('Precision', ascending=False)  # Sort by Precision

# Display results
print("\n" + "="*80)
print("MODEL COMPARISON (sorted by Precision)")
print("="*80)
print(comparison_df.to_string(index=False))

================================================================================
MODEL COMPARISON (sorted by Precision)
================================================================================
                  Model  ROC AUC   PR AUC  Precision   Recall  F1-Score
Linear SVM (Calibrated) 0.752466 0.578212   0.748677 0.234855  0.357549
         Neural Network 0.744404 0.574717   0.646974 0.372614  0.472880
                XGBoost 0.798226 0.645174   0.587927 0.557676  0.572402
    LogReg (ElasticNet) 0.767009 0.592682   0.513437 0.602490  0.554410
           ComplementNB 0.695995 0.551763   0.453316 0.584232  0.510515

In [52]:
# --- Set Method (NO ML) Evaluation ---
# This evaluates simply predicting "1" (Scheduled) if the exact combination
# of (Course, Instructor, Slot, Type) was ever seen in the training data.
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, average_precision_score

print("Evaluating Set Method (NO ML)...")

# 1. Define what columns make a unique combination
key_cols = ['CourseCode', 'Instructor', 'Slot', 'Type']

# 2. Get all positive examples from the training set
train_pos = df_feat.loc[train_mask & (df_feat['Scheduled'] == 1)]

# 3. Create a set of these historical combinations for O(1) lookup time
pos_key_set = set(map(tuple, train_pos[key_cols].values))

# 4. Define our "Set Method" prediction function
def scheduled_ever_lookup(row):
    # Returns 1 if this combo was seen in training positives, 0 otherwise
    combo = (row['CourseCode'], row['Instructor'], row['Slot'], row['Type'])
    return 1 if combo in pos_key_set else 0

# 5. Apply the set method to our test set
test_df_original = df_feat.loc[test_mask]
set_preds = test_df_original.apply(scheduled_ever_lookup, axis=1).values

# For the set method, the "probability" or "score" is just 0 or 1.
set_scores = set_preds

# 6. Calculate metrics for the Set Method
set_roc_auc = roc_auc_score(y_test, set_scores)
set_pr_auc = average_precision_score(y_test, set_scores)
set_precision = precision_score(y_test, set_preds)
set_recall = recall_score(y_test, set_preds)
set_f1 = f1_score(y_test, set_preds)

print(f"Set Method Metrics:")
print(f"  ROC AUC:   {set_roc_auc:.4f}")
print(f"  PR AUC:    {set_pr_auc:.4f}")
print(f"  Precision: {set_precision:.4f}")
print(f"  Recall:    {set_recall:.4f}")
print(f"  F1-Score:  {set_f1:.4f}")

# 7. Add to our comparison dataframe from the previous cell!
# (Assuming 'comparison_df' exists from the previous cells)
if 'comparison_df' in locals():
    # If the set method is already in there, remove it so we don't duplicate
    comparison_df = comparison_df[comparison_df['Model'] != 'Set Method (No ML)']

    set_results = pd.DataFrame([{
        'Model': 'Set Method (No ML)',
        'ROC AUC': set_roc_auc,
        'PR AUC': set_pr_auc,
        'Precision': set_precision,
        'Recall': set_recall,
        'F1-Score': set_f1
    }])

    # Concatenate and re-sort by Precision
    updated_comparison_df = pd.concat([comparison_df, set_results], ignore_index=True)
    updated_comparison_df = updated_comparison_df.sort_values('Precision', ascending=False)

    print("\n" + "="*80)
    print("UPDATED MODEL COMPARISON (including Set Method)")
    print("="*80)
    print(updated_comparison_df.to_string(index=False))
else:
    print("\nWarning: 'comparison_df' not found in environment, could not show updated table.")

Evaluating Set Method (NO ML)...
Set Method Metrics:
  ROC AUC:   0.6729
  PR AUC:    0.4470
  Precision: 0.6654
  Recall:    0.4307
  F1-Score:  0.5229

================================================================================
UPDATED MODEL COMPARISON (including Set Method)
================================================================================
                  Model  ROC AUC   PR AUC  Precision   Recall  F1-Score
Linear SVM (Calibrated) 0.752466 0.578212   0.748677 0.234855  0.357549
     Set Method (No ML) 0.672858 0.447015   0.665385 0.430705  0.522922
         Neural Network 0.744404 0.574717   0.646974 0.372614  0.472880
                XGBoost 0.798226 0.645174   0.587927 0.557676  0.572402
    LogReg (ElasticNet) 0.767009 0.592682   0.513437 0.602490  0.554410
           ComplementNB 0.695995 0.551763   0.453316 0.584232  0.510515